# Generated by Django 3.0.6 on 2020-07-14 19:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salesman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('make', models.CharField(max_length=200)),
                ('bodyType', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('engineType', models.CharField(max_length=200)),
                ('exteriorColor', models.CharField(max_length=200)),
                ('interiorColor', models.CharField(max_length=200)),
                ('driveTrain', models.CharField(max_length=200)),
                ('transmission', models.CharField(max_length=200)),
                ('doors', models.IntegerField()),
                ('vin', models.CharField(max_length=200)),
                ('vehicleID', models.IntegerField()),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='salesman.Salesman')),
            ],
        ),
    ]
