bodyType_choices = {
  'Sedan':'Sedan',
  'Suv':'Suv',
  'Hatchback':'Hatchback',
  'Wagon':'Wagon',
  'Coupe':'Coupe',
  'Minivan':'Minivan',
  'Truck':'Truck',
  'Convertible':'Convertible',
  }


price_choices = {
  '5000':'$5000',
  '10000':'$10,000',
  '15000':'$15,000',
  '20000':'$20,000',
  '25000':'$25,000',
  '30000':'$30,000',
  '35000':'$35,000',
  '40000':'$40,000',
  '45000':'$45,000',
  '50000':'$50,000',
  '55000':'$55,000',
  '60000':'$60,000',
  '65000':'$65,000',
  '70000':'$70,000',
  '75000':'$75,000',
  '80000':'$80,000',
  '85000':'$85,000',
  '90000':'$90,000',
  '95000':'$95,000',
  '100000':'$100,000+',

}

make_choices={

  'Acura':'Acura',
  'Alfa Romeo':'Alfa Romeo',
  'Audi':'Audi',
  'BMW':'BMW',
  'Buick':'Buick',
  'Cadillac':'Cadillac',
  'Chevrolet':'Chevrolet',
  'Chrysler':'Chrysler',
  'Dodge':'Dodge',
  'FIAT':'FIAT',
  'Ford':'Ford',
  'Genesis':'Genesis',
  'GMC':'GMC',
  'Honda':'Honda',
  'Hyundai':'Hyundai',
  'Infiniti':'Infiniti',
  'Jaguar':'Jaguar',
  'Jeep':'Jeep',
  'Kia':'Kia',
  'Land Rover':'Land Rover',
  'Lexus':'Lexus',
  'Lincoln':'Lincoln',
  'Maserati':'Maserati',
  'Mercedes-Benz':'Mercedes-Benz',
  'Mini':'Mini',
  'Mitsubishi':'Mitsubishi',
  'Nissan':'Nissan',
  'Pontiac':'Pontiac',
  'Porsche':'Porsche',
  'Ram':'Ram',
  'Scion':'Scion',
  'smart':'smart',
  'Subaru':'Subaru',
  'Tesla':'Tesla',
  'Toyota':'Toyota',
  'Volkswagen':'Volkswagen',
  'Volvo':'Volvo',
  'Lamborghini':'Lamborghini',
  'Ferrari':'Ferrari',
  'Bugati':'Bugati',
  'Rolls Royce':'Rolls Royce',
  'Mclaren':'Mclaren',
  'Bugati':'Bugati',
  'Bugati':'Bugati',
  'Bentley':'Bentley'
  

}


state_choices = {
        'AK': 'Alaska',
        'AL': 'Alabama',
        'AR': 'Arkansas',
        'AS': 'American Samoa',
        'AZ': 'Arizona',
        'CA': 'California',
        'CO': 'Colorado',
        'CT': 'Connecticut',
        'DC': 'District of Columbia',
        'DE': 'Delaware',
        'FL': 'Florida',
        'GA': 'Georgia',
        'GU': 'Guam',
        'HI': 'Hawaii',
        'IA': 'Iowa',
        'ID': 'Idaho',
        'IL': 'Illinois',
        'IN': 'Indiana',
        'KS': 'Kansas',
        'KY': 'Kentucky',
        'LA': 'Louisiana',
        'MA': 'Massachusetts',
        'MD': 'Maryland',
        'ME': 'Maine',
        'MI': 'Michigan',
        'MN': 'Minnesota',
        'MO': 'Missouri',
        'MP': 'Northern Mariana Islands',
        'MS': 'Mississippi',
        'MT': 'Montana',
        'NA': 'National',
        'NC': 'North Carolina',
        'ND': 'North Dakota',
        'NE': 'Nebraska',
        'NH': 'New Hampshire',
        'NJ': 'New Jersey',
        'NM': 'New Mexico',
        'NV': 'Nevada',
        'NY': 'New York',
        'OH': 'Ohio',
        'OK': 'Oklahoma',
        'OR': 'Oregon',
        'PA': 'Pennsylvania',
        'PR': 'Puerto Rico',
        'RI': 'Rhode Island',
        'SC': 'South Carolina',
        'SD': 'South Dakota',
        'TN': 'Tennessee',
        'TX': 'Texas',
        'UT': 'Utah',
        'VA': 'Virginia',
        'VI': 'Virgin Islands',
        'VT': 'Vermont',
        'WA': 'Washington',
        'WI': 'Wisconsin',
        'WV': 'West Virginia',
        'WY': 'Wyoming'
}